package controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.event.ActionEvent;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;
import application.login;
import application.mainview;
import dao.UserDAO;

import javax.swing.JOptionPane;

import application.emroll;

public class loginController {
	@FXML
	private AnchorPane root;
	@FXML
	private TextField accountin;
	@FXML
	private TextField passwordin;
	@FXML
	private Button loginbtn;
	@FXML
	private Button emrollbtn;

	public static String ac;
	
	// Event Listener on Button[#loginbtn].onAction
	@FXML
	public void login(ActionEvent event) {
		// TODO Autogenerated
		boolean is = UserDAO.Matchaccount(accountin.getText(), passwordin.getText());
		if(is==true) {
			System.out.println("µÇÂ¼³É¹¦");
			//µÇÂ¼³É¹¦
			ac = accountin.getText();
			Stage stage = (Stage) root.getScene().getWindow();
			stage.close();
			mainview r = new mainview();
			r.start(new Stage());
			return ;
		}else {
			//µÇÂ¼Ê§°Ü
			JOptionPane.showMessageDialog(null, "ÕËºÅ»òÃÜÂë´íÎó", null, JOptionPane.ERROR_MESSAGE);
			return ;
		}
	}
	// Event Listener on Button[#emrollbtn].onAction
	@FXML
	public void emroll(ActionEvent event) {
		// TODO Autogenerated
		Stage stage = (Stage) root.getScene().getWindow();
		stage.close();
		emroll r = new emroll();
		r.start(new Stage());
		
	}
}
