package controller;

import application.mainview;
import javafx.fxml.FXML;

import javafx.scene.control.Label;

import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;
import javafx.scene.input.MouseEvent;
import application.*;

public class mainviewController {
	@FXML
	private AnchorPane root;
	@FXML
	private Label deposit;
	@FXML
	private Label withdrawact;
	@FXML
	private Label transferact;
	@FXML
	private Label payrollact;
	@FXML
	private Label interest;

	// Event Listener on Label[#deposit].onMouseClicked
	@FXML
	public void disposit(MouseEvent event) {
		// TODO Autogenerated
		Stage stage = (Stage) root.getScene().getWindow();
		stage.close();
		disposit r = new disposit();
		r.start(new Stage());
	}
	// Event Listener on Label[#withdrawact].onMouseClicked
	@FXML
	public void withdraw(MouseEvent event) {
		// TODO Autogenerated
		Stage stage = (Stage) root.getScene().getWindow();
		stage.close();
		withdraw r = new withdraw();
		r.start(new Stage());
		
	}
	// Event Listener on Label[#transferact].onMouseClicked
	@FXML
	public void transfer(MouseEvent event) {
		// TODO Autogenerated
		Stage stage = (Stage) root.getScene().getWindow();
		stage.close();
		transfer r = new transfer();
		r.start(new Stage());
		
	}
	// Event Listener on Label[#payrollact].onMouseClicked
	@FXML
	public void payroll(MouseEvent event) {
		// TODO Autogenerated
		Stage stage = (Stage) root.getScene().getWindow();
		stage.close();
		payroll r = new payroll();
		r.start(new Stage());		
	}
	// Event Listener on Label[#interest].onMouseClicked
	@FXML
	public void interest(MouseEvent event) {
		// TODO Autogenerated
		
	}
}
