package controller;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.net.URL;
import java.util.List;
import java.util.ResourceBundle;

import javax.swing.JOptionPane;

import application.mainview;
import dao.UserDAO;
import javafx.collections.FXCollections;
import javafx.event.ActionEvent;

import javafx.scene.control.ListView;
import javafx.scene.control.SelectionMode;
import javafx.scene.control.SelectionModel;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;

public class payrollController implements Initializable{
	@FXML
	private AnchorPane root;
	@FXML
	private TextField money;
	@FXML
	private Button confirmbtn;
	@FXML
	private Button backbtn;
	@FXML
	private ListView listview;

	// Event Listener on Button[#confirmbtn].onAction
	@FXML
	public void confirm(ActionEvent event) {
		// TODO Autogenerated
		String t = money.getText();
		boolean flag = true;
		for(int i=0;i<t.length();i++) {
			if(t.charAt(i)=='.') {
				flag = false;
				break;
			}
			if((t.charAt(i)>'9'||t.charAt(i)<'0')&&t.charAt(i)!='.') {
				flag = false;
				break;
			}
		}
		if(flag==false) {
			JOptionPane.showMessageDialog(null, "请输入数字", null, JOptionPane.ERROR_MESSAGE);
			return ;
		}
		float m = Float.valueOf(t);
		@SuppressWarnings("unchecked")
		List<String> list = listview.getSelectionModel().getSelectedItems();
		//进行转账
		Thread th4 =new Thread(new Runnable() {
			@Override
			public void run() {
				// TODO Auto-generated method stub
				synchronized(this) {
					boolean flag = UserDAO.withdrawmoney(-1*m*list.size(), loginController.ac);
					if(flag == false) {
						JOptionPane.showMessageDialog(null, "余额不足", null, JOptionPane.ERROR_MESSAGE);
						return ;
					} else {
						for(int i=0;i<list.size();i++) {
							UserDAO.dispositmoney(m, list.get(i));
						}
						JOptionPane.showMessageDialog(null, "发工资成功", null, JOptionPane.INFORMATION_MESSAGE);
					}
					
				}
			}
		});
		th4.setPriority(1);
		th4.start();
		Stage stage = (Stage) root.getScene().getWindow();
		stage.close();
		mainview r = new mainview();
		r.start(new Stage());		
	}
	// Event Listener on Button[#backbtn].onAction
	@FXML
	public void back(ActionEvent event) {
		// TODO Autogenerated
		Stage stage = (Stage) root.getScene().getWindow();
		stage.close();
		mainview r = new mainview();
		r.start(new Stage());
	}
	
	@SuppressWarnings("unchecked")
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		listview.setItems(FXCollections.observableArrayList(UserDAO.findallecp(loginController.ac)));
		listview.setVisible(true);
		listview.getSelectionModel().setSelectionMode(SelectionMode.MULTIPLE);
	}
}
