package controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javax.swing.JOptionPane;

import application.mainview;
import dao.UserDAO;
import javafx.event.ActionEvent;

import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;

public class transferController {
	@FXML
	private AnchorPane root;
	@FXML
	private TextField money;
	@FXML
	private Button confirmbtn;
	@FXML
	private Button backbtn;
	@FXML
	private TextField account;

	// Event Listener on Button[#confirmbtn].onAction
	@FXML
	public void confirm(ActionEvent event) {
		// TODO Autogenerated
		String t = money.getText();
		boolean flag = true;
		for(int i=0;i<t.length();i++) {
			if(t.charAt(i)=='.') {
				flag = false;
				break;
			}
			if((t.charAt(i)>'9'||t.charAt(i)<'0')&&t.charAt(i)!='.') {
				flag = false;
				break;
			}
		}
		if(flag==false) {
			JOptionPane.showMessageDialog(null, "ÇëÊäÈëÊý×Ö", null, JOptionPane.ERROR_MESSAGE);
			return ;
		}
		if(account.getText().equals(null)) {
			JOptionPane.showMessageDialog(null, "ÇëÊäÈëÕËºÅ", null, JOptionPane.ERROR_MESSAGE);
			return ;
		}
		float m = Float.valueOf(t);
		
		
		//½øÐÐ×ªÕË
		Thread th3 =new Thread(new Runnable() {
			@Override
			public void run() {
				// TODO Auto-generated method stub
				synchronized(this) {
					long start = System.currentTimeMillis();
					boolean flag = UserDAO.withdrawmoney(-m, loginController.ac);
					if(flag == false) {
						JOptionPane.showMessageDialog(null, "Óà¶î²»×ã", null, JOptionPane.ERROR_MESSAGE);
						return ;
					} else {
						boolean find = UserDAO.find(account.getText());
						if(find) {
							UserDAO.dispositmoney(m, account.getText());
						}else {
							System.out.println("ÕËºÅ´íÎó");
							long end = System.currentTimeMillis();
							System.out.println("×ªÕËºÄÊ±£º"+(end-start)/1000+"Ãë");
							JOptionPane.showMessageDialog(null, "ÕËºÅ´íÎó", null, JOptionPane.ERROR_MESSAGE);
							return;
						}
						System.out.println("×ªÕË³É¹¦");
						JOptionPane.showMessageDialog(null, "×ªÕË³É¹¦", null, JOptionPane.INFORMATION_MESSAGE);
					}
					long end = System.currentTimeMillis();
					System.out.println("×ªÕËºÄÊ±£º"+(end-start)/1000+"Ãë");
				}
			}
		});
		th3.setPriority(10);
		th3.start();
		Stage stage = (Stage) root.getScene().getWindow();
		stage.close();
		mainview r = new mainview();
		r.start(new Stage());
		
	}
	// Event Listener on Button[#backbtn].onAction
	@FXML
	public void back(ActionEvent event) {
		// TODO Autogenerated
		Stage stage = (Stage) root.getScene().getWindow();
		stage.close();
		mainview r = new mainview();
		r.start(new Stage());
	}
}
